# Generated by Django 4.0.5 on 2022-06-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amountFollower',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='amountFollowing',
            field=models.IntegerField(null=True),
        ),
    ]
